const playersData = {
  "legends": [
    {"id":1,"name":"ليونيل ميسي","position":"جناح/مهاجم","attack":99,"defense":45,"speed":92,"image":"default.png"},
    {"id":2,"name":"كريستيانو رونالدو","position":"مهاجم","attack":99,"defense":50,"speed":94,"image":"default.png"},
    {"id":3,"name":"بيليه","position":"مهاجم","attack":99,"defense":55,"speed":95,"image":"default.png"},
    {"id":4,"name":"دييجو مارادونا","position":"صانع ألعاب","attack":99,"defense":50,"speed":93,"image":"default.png"},
    {"id":5,"name":"رونالدو نازاريو","position":"مهاجم","attack":98,"defense":40,"speed":97,"image":"default.png"},
    {"id":6,"name":"يوهان كرويف","position":"مهاجم/وسط هجومي","attack":97,"defense":65,"speed":94,"image":"default.png"},
    {"id":7,"name":"زين الدين زيدان","position":"وسط هجومي","attack":96,"defense":70,"speed":86,"image":"default.png"},
    {"id":8,"name":"رونالدينيو","position":"جناح/وسط هجومي","attack":96,"defense":55,"speed":91,"image":"default.png"},
    {"id":9,"name":"ألفريدو دي ستيفانو","position":"مهاجم","attack":96,"defense":80,"speed":89,"image":"default.png"},
    {"id":10,"name":"فيرينتس بوشكاش","position":"مهاجم","attack":98,"defense":50,"speed":84,"image":"default.png"},
    {"id":11,"name":"فرانز بيكنباور","position":"قلب دفاع","attack":88,"defense":99,"speed":83,"image":"default.png"},
    {"id":12,"name":"باولو مالديني","position":"قلب دفاع/ظهير","attack":78,"defense":99,"speed":82,"image":"default.png"},
    {"id":13,"name":"روبرتو كارلوس","position":"ظهير أيسر","attack":87,"defense":94,"speed":95,"image":"default.png"},
    {"id":14,"name":"كافو","position":"ظهير أيمن","attack":89,"defense":93,"speed":95,"image":"default.png"},
    {"id":15,"name":"تشافي","position":"وسط","attack":91,"defense":88,"speed":80,"image":"default.png"},
    {"id":16,"name":"أندريس إنييستا","position":"وسط","attack":93,"defense":82,"speed":86,"image":"default.png"},
    {"id":17,"name":"لوثار ماتيوس","position":"وسط دفاعي","attack":91,"defense":92,"speed":87,"image":"default.png"},
    {"id":18,"name":"ميشيل بلاتيني","position":"وسط هجومي","attack":96,"defense":65,"speed":84,"image":"default.png"},
    {"id":19,"name":"جارينشا","position":"جناح","attack":95,"defense":45,"speed":97,"image":"default.png"},
    {"id":20,"name":"جورج بست","position":"جناح","attack":95,"defense":50,"speed":94,"image":"default.png"},
    {"id":21,"name":"ماركو فان باستن","position":"مهاجم","attack":97,"defense":45,"speed":86,"image":"default.png"},
    {"id":22,"name":"جيرد مولر","position":"مهاجم","attack":98,"defense":40,"speed":80,"image":"default.png"},
    {"id":23,"name":"روماريو","position":"مهاجم","attack":97,"defense":40,"speed":91,"image":"default.png"},
    {"id":24,"name":"تييري هنري","position":"مهاجم/جناح","attack":96,"defense":55,"speed":96,"image":"default.png"},
    {"id":25,"name":"زلاتان إبراهيموفيتش","position":"مهاجم","attack":95,"defense":60,"speed":82,"image":"default.png"},
    {"id":26,"name":"لوكا مودريتش","position":"وسط","attack":90,"defense":88,"speed":84,"image":"default.png"},
    {"id":27,"name":"نيمار","position":"جناح","attack":94,"defense":45,"speed":93,"image":"default.png"},
    {"id":28,"name":"ليف ياشين","position":"حارس","attack":10,"defense":99,"speed":70,"image":"default.png"},
    {"id":29,"name":"بوفون","position":"حارس","attack":10,"defense":98,"speed":68,"image":"default.png"},
    {"id":30,"name":"إيكر كاسياس","position":"حارس","attack":10,"defense":97,"speed":72,"image":"default.png"},
    {"id":31,"name":"سيرجيو راموس","position":"قلب دفاع","attack":82,"defense":96,"speed":84,"image":"default.png"},
    {"id":32,"name":"كارليس بويول","position":"قلب دفاع","attack":72,"defense":97,"speed":79,"image":"default.png"},
    {"id":33,"name":"فيرجيل فان دايك","position":"قلب دفاع","attack":70,"defense":96,"speed":85,"image":"default.png"},
    {"id":34,"name":"توني كروس","position":"وسط","attack":89,"defense":88,"speed":77,"image":"default.png"},
    {"id":35,"name":"ستيفن جيرارد","position":"وسط","attack":91,"defense":87,"speed":85,"image":"default.png"},
    {"id":36,"name":"فرانك لامبارد","position":"وسط","attack":92,"defense":83,"speed":81,"image":"default.png"},
    {"id":37,"name":"بول سكولز","position":"وسط","attack":90,"defense":85,"speed":79,"image":"default.png"},
    {"id":38,"name":"ريفالدو","position":"وسط هجومي","attack":95,"defense":60,"speed":87,"image":"default.png"},
    {"id":39,"name":"كاكا","position":"وسط هجومي","attack":94,"defense":60,"speed":91,"image":"default.png"},
    {"id":40,"name":"واين روني","position":"مهاجم","attack":93,"defense":72,"speed":86,"image":"default.png"},
    {"id":41,"name":"محمد صلاح","position":"جناح أيمن","attack":95,"defense":55,"speed":96,"image":"default.png"},
    {"id":42,"name":"كيليان مبابي","position":"مهاجم","attack":96,"defense":45,"speed":99,"image":"default.png"},
    {"id":43,"name":"إيرلينج هالاند","position":"مهاجم","attack":97,"defense":55,"speed":91,"image":"default.png"},
    {"id":44,"name":"لويس سواريز","position":"مهاجم","attack":96,"defense":60,"speed":84,"image":"default.png"},
    {"id":45,"name":"روبرت ليفاندوفسكي","position":"مهاجم","attack":97,"defense":55,"speed":82,"image":"default.png"},
    {"id":46,"name":"ديفيد بيكهام","position":"وسط أيمن","attack":91,"defense":78,"speed":82,"image":"default.png"},
    {"id":47,"name":"أشلي كول","position":"ظهير أيسر","attack":78,"defense":94,"speed":89,"image":"default.png"},
    {"id":48,"name":"فيليب لام","position":"ظهير أيمن/أيسر","attack":82,"defense":95,"speed":86,"image":"default.png"},
    {"id":49,"name":"مانويل نوير","position":"حارس","attack":15,"defense":98,"speed":78,"image":"default.png"},
    {"id":50,"name":"أوليفر كان","position":"حارس","attack":10,"defense":98,"speed":71,"image":"default.png"}
  ],
  "normals": [
    {"id":51,"name":"محمد هاني","position":"ظهير أيمن","attack":68,"defense":80,"speed":79,"image":"default.png"},
    {"id":52,"name":"عمر كمال عبد الواحد","position":"ظهير أيمن","attack":72,"defense":79,"speed":80,"image":"default.png"},
    {"id":53,"name":"رامي ربيعة","position":"قلب دفاع","attack":55,"defense":82,"speed":72,"image":"default.png"},
    {"id":54,"name":"ياسر إبراهيم","position":"قلب دفاع","attack":52,"defense":81,"speed":70,"image":"default.png"},
    {"id":55,"name":"مصطفى العش","position":"قلب دفاع","attack":50,"defense":78,"speed":71,"image":"default.png"},
    {"id":56,"name":"أحمد نبيل كوكا","position":"وسط/ظهير","attack":74,"defense":79,"speed":78,"image":"default.png"},
    {"id":57,"name":"مروان عطية","position":"وسط دفاعي","attack":73,"defense":82,"speed":75,"image":"default.png"},
    {"id":58,"name":"إمام عاشور","position":"وسط","attack":84,"defense":79,"speed":83,"image":"default.png"},
    {"id":59,"name":"محمد مجدي أفشة","position":"وسط هجومي","attack":83,"defense":66,"speed":74,"image":"default.png"},
    {"id":60,"name":"طاهر محمد طاهر","position":"جناح","attack":81,"defense":64,"speed":84,"image":"default.png"},
    {"id":61,"name":"حسين الشحات","position":"جناح","attack":82,"defense":65,"speed":85,"image":"default.png"},
    {"id":62,"name":"وسام أبو علي","position":"مهاجم","attack":84,"defense":45,"speed":82,"image":"default.png"},
    {"id":63,"name":"مصطفى شلبي","position":"جناح","attack":79,"defense":60,"speed":83,"image":"default.png"},
    {"id":64,"name":"ناصر ماهر","position":"وسط هجومي","attack":80,"defense":63,"speed":78,"image":"default.png"},
    {"id":65,"name":"ناصر منسي","position":"مهاجم","attack":82,"defense":48,"speed":80,"image":"default.png"},
    {"id":66,"name":"محمد شحاتة","position":"وسط","attack":76,"defense":78,"speed":77,"image":"default.png"},
    {"id":67,"name":"محمد عواد","position":"حارس","attack":10,"defense":81,"speed":68,"image":"default.png"},
    {"id":68,"name":"محمد صبحي","position":"حارس","attack":10,"defense":82,"speed":70,"image":"default.png"},
    {"id":69,"name":"أحمد الشناوي","position":"حارس","attack":10,"defense":83,"speed":68,"image":"default.png"},
    {"id":70,"name":"محمد بسام","position":"حارس","attack":10,"defense":81,"speed":67,"image":"default.png"},
    {"id":71,"name":"داني سيبايوس","position":"وسط","attack":81,"defense":75,"speed":75,"image":"default.png"},
    {"id":72,"name":"لوكاس فاسكيز","position":"ظهير/جناح","attack":79,"defense":77,"speed":82,"image":"default.png"},
    {"id":73,"name":"فيرلاند ميندي","position":"ظهير أيسر","attack":71,"defense":84,"speed":86,"image":"default.png"},
    {"id":74,"name":"فران جارسيا","position":"ظهير أيسر","attack":72,"defense":81,"speed":85,"image":"default.png"},
    {"id":75,"name":"إيريك جارسيا","position":"قلب دفاع","attack":63,"defense":82,"speed":72,"image":"default.png"},
    {"id":76,"name":"فيرمين لوبيز","position":"وسط","attack":83,"defense":74,"speed":81,"image":"default.png"},
    {"id":77,"name":"جافي","position":"وسط","attack":82,"defense":81,"speed":79,"image":"default.png"},
    {"id":78,"name":"فيران توريس","position":"جناح","attack":83,"defense":55,"speed":84,"image":"default.png"},
    {"id":79,"name":"أنسو فاتي","position":"جناح","attack":80,"defense":52,"speed":84,"image":"default.png"},
    {"id":80,"name":"ريتشارليسون","position":"مهاجم","attack":84,"defense":50,"speed":82,"image":"default.png"},
    {"id":81,"name":"جابرييل جيسوس","position":"مهاجم","attack":85,"defense":52,"speed":84,"image":"default.png"},
    {"id":82,"name":"كالوم ويلسون","position":"مهاجم","attack":83,"defense":48,"speed":80,"image":"default.png"},
    {"id":83,"name":"هارفي إليوت","position":"وسط","attack":80,"defense":72,"speed":79,"image":"default.png"},
    {"id":84,"name":"كيرنان ديوسبري هال","position":"وسط","attack":78,"defense":76,"speed":77,"image":"default.png"},
    {"id":85,"name":"أليكس إيوبي","position":"وسط","attack":80,"defense":71,"speed":81,"image":"default.png"},
    {"id":86,"name":"آرون وان بيساكا","position":"ظهير أيمن","attack":68,"defense":84,"speed":85,"image":"default.png"},
    {"id":87,"name":"تايريك ميتشل","position":"ظهير أيسر","attack":67,"defense":80,"speed":83,"image":"default.png"},
    {"id":88,"name":"لويس دانك","position":"قلب دفاع","attack":58,"defense":84,"speed":66,"image":"default.png"},
    {"id":89,"name":"جيمس تاركوفسكي","position":"قلب دفاع","attack":57,"defense":83,"speed":65,"image":"default.png"},
    {"id":90,"name":"أوناي سيمون","position":"حارس","attack":10,"defense":85,"speed":70,"image":"default.png"},
    {"id":91,"name":"جوردان بيكفورد","position":"حارس","attack":10,"defense":85,"speed":72,"image":"default.png"},
    {"id":92,"name":"بيرند لينو","position":"حارس","attack":10,"defense":84,"speed":69,"image":"default.png"},
    {"id":93,"name":"يوسف النصيري","position":"مهاجم","attack":83,"defense":45,"speed":84,"image":"default.png"},
    {"id":94,"name":"يوسف عطال","position":"ظهير أيمن","attack":74,"defense":78,"speed":85,"image":"default.png"},
    {"id":95,"name":"إسماعيل بن ناصر","position":"وسط","attack":81,"defense":82,"speed":80,"image":"default.png"},
    {"id":96,"name":"سفيان أمرابط","position":"وسط دفاعي","attack":76,"defense":84,"speed":75,"image":"default.png"},
    {"id":97,"name":"أيوب الكعبي","position":"مهاجم","attack":82,"defense":45,"speed":81,"image":"default.png"},
    {"id":98,"name":"ريان آيت نوري","position":"ظهير أيسر","attack":75,"defense":81,"speed":87,"image":"default.png"},
    {"id":99,"name":"سفيان بوفال","position":"جناح","attack":81,"defense":50,"speed":84,"image":"default.png"},
    {"id":100,"name":"جويلينتون","position":"وسط","attack":79,"defense":81,"speed":79,"image":"default.png"}
  ],
  "veryWeak": [
    {"id":101,"name":"محمد خميس","position":"حارس","attack":10,"defense":58,"speed":55,"image":"default.png"},
    {"id":102,"name":"يوسف حسن","position":"مهاجم","attack":60,"defense":30,"speed":65,"image":"default.png"},
    {"id":103,"name":"أحمد ياسر ريان","position":"مهاجم","attack":67,"defense":35,"speed":72,"image":"default.png"},
    {"id":104,"name":"كريم بامبو","position":"جناح","attack":65,"defense":35,"speed":75,"image":"default.png"},
    {"id":105,"name":"محمد عنتر","position":"جناح","attack":62,"defense":40,"speed":70,"image":"default.png"},
    {"id":106,"name":"إسلام جابر","position":"وسط","attack":55,"defense":58,"speed":60,"image":"default.png"},
    {"id":107,"name":"أحمد رفعت","position":"جناح","attack":68,"defense":35,"speed":78,"image":"default.png"},
    {"id":108,"name":"أحمد الشيخ","position":"وسط هجومي","attack":65,"defense":40,"speed":65,"image":"default.png"},
    {"id":109,"name":"محمد هلال","position":"وسط","attack":60,"defense":55,"speed":63,"image":"default.png"},
    {"id":110,"name":"حازم إمام","position":"ظهير","attack":50,"defense":62,"speed":60,"image":"default.png"},
    {"id":111,"name":"محمد عبد السلام","position":"قلب دفاع","attack":35,"defense":65,"speed":50,"image":"default.png"},
    {"id":112,"name":"مصطفى الزناري","position":"قلب دفاع","attack":40,"defense":67,"speed":55,"image":"default.png"},
    {"id":113,"name":"كريم حافظ","position":"ظهير أيسر","attack":55,"defense":63,"speed":70,"image":"default.png"},
    {"id":114,"name":"محمد صادق","position":"وسط","attack":60,"defense":55,"speed":68,"image":"default.png"},
    {"id":115,"name":"عبد الرحمن مجدي","position":"جناح","attack":67,"defense":35,"speed":75,"image":"default.png"},
    {"id":116,"name":"أوستن أموتو","position":"مهاجم","attack":64,"defense":30,"speed":65,"image":"default.png"},
    {"id":117,"name":"محمد فوزي","position":"حارس","attack":10,"defense":62,"speed":50,"image":"default.png"},
    {"id":118,"name":"محمود جاد","position":"حارس","attack":10,"defense":65,"speed":55,"image":"default.png"},
    {"id":119,"name":"جون فيكتور","position":"حارس","attack":10,"defense":68,"speed":60,"image":"default.png"},
    {"id":120,"name":"أحمد سامي","position":"قلب دفاع","attack":40,"defense":68,"speed":58,"image":"default.png"},
    {"id":121,"name":"أحمد توفيق","position":"وسط","attack":55,"defense":65,"speed":62,"image":"default.png"},
    {"id":122,"name":"إسلام محارب","position":"جناح","attack":60,"defense":38,"speed":70,"image":"default.png"},
    {"id":123,"name":"محمد رضا","position":"وسط","attack":62,"defense":55,"speed":65,"image":"default.png"},
    {"id":124,"name":"مروان حمدي","position":"مهاجم","attack":66,"defense":30,"speed":68,"image":"default.png"},
    {"id":125,"name":"أحمد أمين أوفا","position":"مهاجم","attack":68,"defense":32,"speed":73,"image":"default.png"},
    {"id":126,"name":"محمد شكري","position":"ظهير","attack":55,"defense":62,"speed":72,"image":"default.png"},
    {"id":127,"name":"محمد نصر","position":"قلب دفاع","attack":35,"defense":63,"speed":55,"image":"default.png"},
    {"id":128,"name":"عمر الساعي","position":"وسط","attack":58,"defense":55,"speed":65,"image":"default.png"},
    {"id":129,"name":"فخري لاكاي","position":"مهاجم","attack":65,"defense":30,"speed":66,"image":"default.png"},
    {"id":130,"name":"عبد الكبير الوادي","position":"جناح","attack":64,"defense":35,"speed":74,"image":"default.png"},
    {"id":131,"name":"محمد فاروق","position":"جناح","attack":62,"defense":40,"speed":70,"image":"default.png"},
    {"id":132,"name":"أحمد مدبولي","position":"وسط هجومي","attack":63,"defense":42,"speed":65,"image":"default.png"},
    {"id":133,"name":"خالد صبحي","position":"قلب دفاع","attack":35,"defense":66,"speed":50,"image":"default.png"},
    {"id":134,"name":"محمد رضا بوبو","position":"وسط","attack":64,"defense":60,"speed":68,"image":"default.png"},
    {"id":135,"name":"أحمد عبد القادر","position":"جناح","attack":68,"defense":35,"speed":76,"image":"default.png"},
    {"id":136,"name":"محمد شريف","position":"مهاجم","attack":69,"defense":35,"speed":75,"image":"default.png"},
    {"id":137,"name":"علي جبر","position":"قلب دفاع","attack":30,"defense":70,"speed":45,"image":"default.png"},
    {"id":138,"name":"محمد أبو جبل","position":"حارس","attack":10,"defense":70,"speed":50,"image":"default.png"},
    {"id":139,"name":"محمود علاء","position":"قلب دفاع","attack":35,"defense":68,"speed":48,"image":"default.png"},
    {"id":140,"name":"أحمد عيد","position":"ظهير","attack":50,"defense":60,"speed":70,"image":"default.png"},
    {"id":141,"name":"محمد أشرف","position":"ظهير","attack":48,"defense":62,"speed":65,"image":"default.png"},
    {"id":142,"name":"عمرو السيسي","position":"وسط","attack":55,"defense":64,"speed":60,"image":"default.png"},
    {"id":143,"name":"صلاح محسن","position":"مهاجم","attack":66,"defense":30,"speed":72,"image":"default.png"}
  ],
  "coaches": [
    {"name":"بيب جوارديولا","bonus":15,"type":"legend"},
    {"name":"كارلو أنشيلوتي","bonus":12,"type":"legend"},
    {"name":"زين الدين زيدان","bonus":10,"type":"legend"},
    {"name":"يورغن كلوب","bonus":12,"type":"legend"},
    {"name":"رانجنيك","bonus":5,"type":"normal"},
    {"name":"أنطونيو كونتي","bonus":6,"type":"normal"},
    {"name":"ماسيميليانو أليجري","bonus":4,"type":"normal"},
    {"name":"ماوريسيو بوكيتينو","bonus":5,"type":"normal"}
  ],
  "formations": {
    "4-3-3": {"goalkeeper":1,"defenders":4,"midfielders":3,"attackers":3},
    "4-4-2": {"goalkeeper":1,"defenders":4,"midfielders":4,"attackers":2},
    "3-5-2": {"goalkeeper":1,"defenders":3,"midfielders":5,"attackers":2}
  }
};